# a short string to identify the bridge
Identifier = "BTC2ETH"

# administrators who can do admin work like maintain blacklist etc.
Admins = [
	"0x3dfaef310a1044fd7d96750b42b44cf3775c00bf",
	"0x46cbe22b687d4b72c8913e4784dfe5b20fdc2b0e"
]

# modgodb database connection config (server only)
[MongoDB]
DBURL = "localhost:27017"
DBName = "databasename"
UserName = "username"
Password = "password"

# bridge API service (server only)
[APIServer]
# listen port
Port = 11556
# CORS config
AllowedOrigins = []

# oracle config (oracle only)
[Oracle]
# post swap register RPC requests to this server
ServerAPIAddress = "http://127.0.0.1:11556/rpc"

# customize fees in building btc transaction (server only)
[BtcExtra]
MinRelayFee   = 400
RelayFeePerKb = 2000
# aggregate if have more than so many utxos
UtxoAggregateMinCount = 10
# aggregate if have more than so many value
UtxoAggregateMinValue = 100000 # unit satoshi
# aggreate to this address
UtxoAggregateToAddress = "mfwPnCuht2b4Lvb5XTds4Rvzy3jZ2ZWrBL"

# source chain config
[SrcChain]
BlockChain = "Bitcoin"
NetID = "TestNet3"

# source token config
[SrcToken]
# ID must be ERC20 if source token is erc20 token
ID = "BTC"
Name = "Bitcoin Coin"
Symbol = "BTC"
Decimals = 8
Description = "Bitcoin Coin"
# if ID is ERC20, this is the erc20 token's contract address
ContractAddress = ""
# deposit to this address to make swap
DepositAddress = "mfwPnCuht2b4Lvb5XTds4Rvzy3jZ2ZWrBL"
# withdraw from this address
DcrmAddress = "mfwPnCuht2b4Lvb5XTds4Rvzy3jZ2ZWrBL"
# tx should be in chain with at least so many confirmations to be valid on source chain
Confirmations = 0 # suggest >= 6 for Mainnet
# maximum deposit value
MaximumSwap = 1000.0
# minimum deposit value
MinimumSwap = 0.00001
# calced deposit fee = deposit value * this rate (when in [min, max] deposit fee range)
SwapFeeRate = 0.001
# maximum deposit fee, if calced deposit fee is larger than this fee, then use this value as deposit fee
MaximumSwapFee = 0.01
# minimum deposit fee, if calced deposit fee is smaller than this fee, then use this value as deposit fee
MinimumSwapFee = 0.00001
# only tx with block height >= this initial height should be considered valid on source chain
InitialHeight = 0
# plus this percentage of gas price to make tx more easier to be mined in source chain
# corresponding to send asset on source chain (eg. BTC) for withdrawing
PlusGasPricePercentage = 15 # plus 15% gas price
# if deposit value is larger than this value then need more verify strategy
BigValueThreshold = 5.0
# disable deposit function if this flag is true
DisableSwap = false

# source blockchain gateway config
[SrcGateway]
APIAddress = ["http://47.107.50.83:3002"]

# dest chain config
[DestChain]
BlockChain = "Ethereum"
NetID = "Rinkeby"

# dest token config
[DestToken]
ID = "mBTC"
Name = "SMPC Bitcoin"
Symbol = "mBTC"
Decimals = 8
Description = "cross chain bridge BTC with mBTC"
# mapping erc20 token address
ContractAddress = "0x61b8c4d6d28d5f7edadbea5456db3b4f7f836b64"
# mapping erc20 token creator
DcrmAddress = "0xbF0A46d3700E23a98F38079cE217742c92Bb66bC"
# tx should be in chain with at least so many confirmations to be valid on dest chain
Confirmations = 0 # suggest >= 33 for Mainnet
# maximum withdraw value
MaximumSwap = 100.0
# minimum withdraw value
MinimumSwap = 0.00001
# calced withdraw fee = withdraw value * this rate (when in [min, max] withdraw fee range)
SwapFeeRate = 0.001
# maximum withdraw fee, if calced withdraw fee is larger than this fee, then use this value as withdraw fee
MaximumSwapFee = 0.01
# minimum withdraw fee, if calced withdraw fee is smaller than this fee, then use this value as withdraw fee
MinimumSwapFee = 0.00001
# only tx with block height >= this initial height should be considered valid on dest chain
InitialHeight = 0
# plus this percentage of gas price to make tx more easier to be mined in dest chain
# corresponding to send mapping token on dest chain (eg. mBTC) for depositing
PlusGasPricePercentage = 1 # plus 1% gas price
# if withdraw value is larger than this value then need more verify strategy
BigValueThreshold = 50.0
# disable withdraw function if this flag is true
DisableSwap = false

# dest blockchain gateway config
[DestGateway]
APIAddress = ["http://5.189.139.168:8018"]

# DCRM config
[Dcrm]
# server dcrm user (initiator of dcrm sign)
ServerAccount = "0x00c37841378920E2BA5151a5d1E074Cf367586c4"

# dcrm group ID
GroupID = "74245ef03937fa75b979bdaa6a5952a93f53e021e0832fca4c2ad8952572c9b70f49e291de7e024b0f7fc54ec5875210db2ac775dba44448b3972b75af074d17"

# dcrm account public key
Pubkey = "045c8648793e4867af465691685000ae841dccab0b011283139d2eae454b569d5789f01632e13a75a5aad8480140e895dd671cae3639f935750bea7ae4b5a2512e"

# dcrm sub groups for signing (server only)
SignGroups = [
	"38a93f457c793ac3ee242b2c050a403774738e6558cfaa620fe5577bb15a28f63c39adcc0778497e5009a9ee776a0778ffcad4e95827e69efa21b893b8a78793",
	"bb1dfe1ec046cc3a3b88408ae03976aabffe459b40e5def09e76f5d4c7a917133241da9da7fc05e3e172fab54ce3129a9a492d52a5a09494d0b9c1e608f661bf"
]

# dcrm threshold (NeededOracles=2,TotalOracles=3 represent '2/3' threshold)
NeededOracles = 2
TotalOracles = 3

# dcrm mode (0:managed 1:private)
Mode = 0

# dcrm user keystore and password file (suggest using absolute path)
KeystoreFile = "/home/xxx/accounts/keystore1"
PasswordFile = "/home/xxx/accounts/password1"

# dcrm backend node (gdcrm node RPC address)
RPCAddress = "http://127.0.0.1:2922"
