# a short string to identify the bridge
Identifier = "BLOCK2ETH"

# administrators who can do admin work like maintain blacklist etc.
Admins = [
	"0x3dfaef310a1044fd7d96750b42b44cf3775c00bf",
	"0x46cbe22b687d4b72c8913e4784dfe5b20fdc2b0e"
]

# modgodb database connection config (server only)
[MongoDB]
DBURL = "localhost:27017"
DBName = "databasename"
UserName = "username"
Password = "password"

# bridge API service (server only)
[APIServer]
# listen port
Port = 11556
# CORS config
AllowedOrigins = []

# oracle config (oracle only)
[Oracle]
# post swap register RPC requests to this server
ServerAPIAddress = "http://127.0.0.1:11556/rpc"

# customize fees in building btc transaction (btc only)
[BtcExtra]
# minimum relay fee of tx (much greater than BTC!!!)
MinRelayFee = 3000
# relay fee per kilobytes
MinRelayFeePerKb = 10000
# maximum relay fee per kilobytes
MaxRelayFeePerKb = 500000
# plus percentage of estimate fee to speed tx packing
PlusFeePercentage = 0
# estimate smart fee with such many target blocks
EstimateFeeBlocks = 6
# aggregate if have more than so many utxos
UtxoAggregateMinCount = 20
# aggregate if have more than so many value
UtxoAggregateMinValue = 1000000 # unit satoshi
# aggreate to this address
UtxoAggregateToAddress = "BpeGP9ooFTGSsdcysmMMgbRCqYQgpjrCsE"

# source chain config
[SrcChain]
BlockChain = "BLOCK"
NetID = "Mainnet"
# tx should be in chain with at least so many confirmations to be valid on source chain
Confirmations = 0 # suggest >= 6 for Mainnet
# only tx with block height >= this initial height should be considered valid on source chain
InitialHeight = 0
# whether enable scan blocks and register swaps
EnableScan = false

# source blockchain gateway config
[SrcGateway]
APIAddress = ["5.189.139.168:51515"]
[SrcGateway.Extras]
[SrcGateway.Extras.BlockExtra]
UTXOAPIAddresses = ["https://plugin-dev.core.cloudchainsinc.com"]
[[SrcGateway.Extras.BlockExtra.CoreAPIs]]
APIAddress:"5.189.139.168:51515"
RPCUser:"xxmm"
RPCPassword:"123456"
DisableTLS: true

# dest chain config
[DestChain]
BlockChain = "Ethereum"
NetID = "Rinkeby"
# tx should be in chain with at least so many confirmations to be valid on source chain
Confirmations = 0 # suggest >= 30 for Mainnet
# only tx with block height >= this initial height should be considered valid on source chain
InitialHeight = 0
# whether enable scan blocks and register swaps
EnableScan = false

# dest blockchain gateway config
[DestGateway]
APIAddress = ["http://5.189.139.168:8018"]

# DCRM config
[Dcrm]
# disable flag
Disable = false

# dcrm group ID
GroupID = "74245ef03937fa75b979bdaa6a5952a93f53e021e0832fca4c2ad8952572c9b70f49e291de7e024b0f7fc54ec5875210db2ac775dba44448b3972b75af074d17"

# dcrm threshold (NeededOracles=2,TotalOracles=3 represent '2/3' threshold)
NeededOracles = 2
TotalOracles = 3

# dcrm mode (0:managed 1:private)
Mode = 0

# initiators of dcrm sign
Initiators = [
	"0x00c37841378920E2BA5151a5d1E074Cf367586c4",
	"0x897a9980808a2cae0d09ff693f02a4f80abb2233"
]

# DCRM other initiators nodes config (server only)
[[Dcrm.OtherNodes]]
# dcrm sub groups for signing
SignGroups = [
	"38a93f457c793ac3ee242b2c050a403774738e6558cfaa620fe5577bb15a28f63c39adcc0778497e5009a9ee776a0778ffcad4e95827e69efa21b893b8a78793",
	"bb1dfe1ec046cc3a3b88408ae03976aabffe459b40e5def09e76f5d4c7a917133241da9da7fc05e3e172fab54ce3129a9a492d52a5a09494d0b9c1e608f661bf"
]

# dcrm user keystore and password file (suggest using absolute path)
KeystoreFile = "/home/xxx/accounts/keystore2"
PasswordFile = "/home/xxx/accounts/password2"

# dcrm backend node (gdcrm node RPC address)
RPCAddress = "http://127.0.0.1:2922"

# DCRM default node config
[Dcrm.DefaultNode]
# dcrm sub groups for signing (server only)
SignGroups = [
	"38a93f457c793ac3ee242b2c050a403774738e6558cfaa620fe5577bb15a28f63c39adcc0778497e5009a9ee776a0778ffcad4e95827e69efa21b893b8a78793",
	"bb1dfe1ec046cc3a3b88408ae03976aabffe459b40e5def09e76f5d4c7a917133241da9da7fc05e3e172fab54ce3129a9a492d52a5a09494d0b9c1e608f661bf"
]

# dcrm user keystore and password file (suggest using absolute path)
KeystoreFile = "/home/xxx/accounts/keystore1"
PasswordFile = "/home/xxx/accounts/password1"

# dcrm backend node (gdcrm node RPC address)
RPCAddress = "http://127.0.0.1:2921"
